apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-db-deployment
####################################### 
# same structure of replicaset  
####################################### 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webpage 
  template:
    metadata:
      labels:
        name: webpage 
    spec:
        containers:
        # the name of container
        - name: web-app
        # the docker image
          image: jadsonjs/web-app-db:v2
          ports:
          # port on the container
          - containerPort: 8080
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                 name: app-db-secret
                 key: name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: pass


# continuous same file
---

apiVersion: v1
kind: Service
metadata:
  name: web-app-db-service
spec:
  # select the pods to export in this service
  selector:
    name: webpage
  ports:
    # container port
    - port: 80
      # redirect service port to container port
      targetPort: 8080
      protocol: TCP
      # fix the service node port
      nodePort: 30000
  type: NodePort




